# -*- coding: utf-8 -*-

ATTENDEE_CONFIRMED = 'confirmed'
ATTENDEE_UNCONFIRMED = 'unconfirmed'
ATTENDEE_CANCELLED = 'cancelled'

TEXT_FIELD = 'text'
TEXTAREA_FIELD = 'textarea'
CHECKBOX_FIELD = 'checkbox'
EMAIL_FIELD = 'email'
SELECT_FIELD = 'select'
RADIOBUTTON_FIELD = 'radiobutton'
PHONE_FIELD = 'phone'

RECURRING_NEVER    = 0
RECURRING_DAILY    = 1
RECURRING_WEEKDAYS = 2
RECURRING_WEEKLY   = 3
RECURRING_MONTHLY  = 4
RECURRING_YEARLY   = 5

CURRENCY_DKK = 'DKK'
CURRENCY_EUR = 'EUR'

EVENT_STATUS_OPEN = 'open'
EVENT_STATUS_CLOSED = 'closed'

CSV_EXPORT = 0
PDF_EXPORT = 1
XLS_EXPORT = 2

REGISTRATION_DATA = 0
BOOKING_DATA = 1
